# Generated by Django 4.1.3 on 2022-12-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dicount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
