# Generated by Django 4.1.3 on 2023-01-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='specifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
    ]
