# Generated by Django 4.1.3 on 2022-12-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_dicount_price_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.FloatField(default=25000),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
