# Generated by Django 4.1.3 on 2022-12-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_item_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='dicount_price',
            new_name='discount_price',
        ),
    ]
