# Generated by Django 4.1.3 on 2022-12-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_balance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=30000.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.SlugField(blank=True),
        ),
    ]
