# Generated by Django 4.1.3 on 2022-12-07 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_balance_balance_alter_order_ref_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='email',
        ),
        migrations.AddField(
            model_name='refund',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
